// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/url_shortener.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	URLShortener_ShortenURL_FullMethodName        = "/urlshortener.URLShortener/ShortenURL"
	URLShortener_GetOriginalURL_FullMethodName    = "/urlshortener.URLShortener/GetOriginalURL"
	URLShortener_ListShortenedURLs_FullMethodName = "/urlshortener.URLShortener/ListShortenedURLs"
	URLShortener_BatchShortenURLs_FullMethodName  = "/urlshortener.URLShortener/BatchShortenURLs"
	URLShortener_MonitorURLStats_FullMethodName   = "/urlshortener.URLShortener/MonitorURLStats"
)

// URLShortenerClient is the client API for URLShortener service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Define the URL shortening service
type URLShortenerClient interface {
	// Shorten a URL
	ShortenURL(ctx context.Context, in *ShortenRequest, opts ...grpc.CallOption) (*ShortenResponse, error)
	// Retrieve original URL
	GetOriginalURL(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// List all shortened URLs
	ListShortenedURLs(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ShortenResponse], error)
	// Batch shorten URLs
	BatchShortenURLs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ShortenRequest, BatchResponse], error)
	// Monitor URL statistics
	MonitorURLStats(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StatsRequest, StatsResponse], error)
}

type uRLShortenerClient struct {
	cc grpc.ClientConnInterface
}

func NewURLShortenerClient(cc grpc.ClientConnInterface) URLShortenerClient {
	return &uRLShortenerClient{cc}
}

func (c *uRLShortenerClient) ShortenURL(ctx context.Context, in *ShortenRequest, opts ...grpc.CallOption) (*ShortenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShortenResponse)
	err := c.cc.Invoke(ctx, URLShortener_ShortenURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uRLShortenerClient) GetOriginalURL(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, URLShortener_GetOriginalURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uRLShortenerClient) ListShortenedURLs(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ShortenResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &URLShortener_ServiceDesc.Streams[0], URLShortener_ListShortenedURLs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListRequest, ShortenResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type URLShortener_ListShortenedURLsClient = grpc.ServerStreamingClient[ShortenResponse]

func (c *uRLShortenerClient) BatchShortenURLs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ShortenRequest, BatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &URLShortener_ServiceDesc.Streams[1], URLShortener_BatchShortenURLs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ShortenRequest, BatchResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type URLShortener_BatchShortenURLsClient = grpc.ClientStreamingClient[ShortenRequest, BatchResponse]

func (c *uRLShortenerClient) MonitorURLStats(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StatsRequest, StatsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &URLShortener_ServiceDesc.Streams[2], URLShortener_MonitorURLStats_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StatsRequest, StatsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type URLShortener_MonitorURLStatsClient = grpc.BidiStreamingClient[StatsRequest, StatsResponse]

// URLShortenerServer is the server API for URLShortener service.
// All implementations must embed UnimplementedURLShortenerServer
// for forward compatibility.
//
// Define the URL shortening service
type URLShortenerServer interface {
	// Shorten a URL
	ShortenURL(context.Context, *ShortenRequest) (*ShortenResponse, error)
	// Retrieve original URL
	GetOriginalURL(context.Context, *GetRequest) (*GetResponse, error)
	// List all shortened URLs
	ListShortenedURLs(*ListRequest, grpc.ServerStreamingServer[ShortenResponse]) error
	// Batch shorten URLs
	BatchShortenURLs(grpc.ClientStreamingServer[ShortenRequest, BatchResponse]) error
	// Monitor URL statistics
	MonitorURLStats(grpc.BidiStreamingServer[StatsRequest, StatsResponse]) error
	mustEmbedUnimplementedURLShortenerServer()
}

// UnimplementedURLShortenerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedURLShortenerServer struct{}

func (UnimplementedURLShortenerServer) ShortenURL(context.Context, *ShortenRequest) (*ShortenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShortenURL not implemented")
}
func (UnimplementedURLShortenerServer) GetOriginalURL(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOriginalURL not implemented")
}
func (UnimplementedURLShortenerServer) ListShortenedURLs(*ListRequest, grpc.ServerStreamingServer[ShortenResponse]) error {
	return status.Error(codes.Unimplemented, "method ListShortenedURLs not implemented")
}
func (UnimplementedURLShortenerServer) BatchShortenURLs(grpc.ClientStreamingServer[ShortenRequest, BatchResponse]) error {
	return status.Error(codes.Unimplemented, "method BatchShortenURLs not implemented")
}
func (UnimplementedURLShortenerServer) MonitorURLStats(grpc.BidiStreamingServer[StatsRequest, StatsResponse]) error {
	return status.Error(codes.Unimplemented, "method MonitorURLStats not implemented")
}
func (UnimplementedURLShortenerServer) mustEmbedUnimplementedURLShortenerServer() {}
func (UnimplementedURLShortenerServer) testEmbeddedByValue()                      {}

// UnsafeURLShortenerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to URLShortenerServer will
// result in compilation errors.
type UnsafeURLShortenerServer interface {
	mustEmbedUnimplementedURLShortenerServer()
}

func RegisterURLShortenerServer(s grpc.ServiceRegistrar, srv URLShortenerServer) {
	// If the following call panics, it indicates UnimplementedURLShortenerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&URLShortener_ServiceDesc, srv)
}

func _URLShortener_ShortenURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLShortenerServer).ShortenURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: URLShortener_ShortenURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLShortenerServer).ShortenURL(ctx, req.(*ShortenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _URLShortener_GetOriginalURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLShortenerServer).GetOriginalURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: URLShortener_GetOriginalURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLShortenerServer).GetOriginalURL(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _URLShortener_ListShortenedURLs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(URLShortenerServer).ListShortenedURLs(m, &grpc.GenericServerStream[ListRequest, ShortenResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type URLShortener_ListShortenedURLsServer = grpc.ServerStreamingServer[ShortenResponse]

func _URLShortener_BatchShortenURLs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(URLShortenerServer).BatchShortenURLs(&grpc.GenericServerStream[ShortenRequest, BatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type URLShortener_BatchShortenURLsServer = grpc.ClientStreamingServer[ShortenRequest, BatchResponse]

func _URLShortener_MonitorURLStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(URLShortenerServer).MonitorURLStats(&grpc.GenericServerStream[StatsRequest, StatsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type URLShortener_MonitorURLStatsServer = grpc.BidiStreamingServer[StatsRequest, StatsResponse]

// URLShortener_ServiceDesc is the grpc.ServiceDesc for URLShortener service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var URLShortener_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "urlshortener.URLShortener",
	HandlerType: (*URLShortenerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShortenURL",
			Handler:    _URLShortener_ShortenURL_Handler,
		},
		{
			MethodName: "GetOriginalURL",
			Handler:    _URLShortener_GetOriginalURL_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListShortenedURLs",
			Handler:       _URLShortener_ListShortenedURLs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BatchShortenURLs",
			Handler:       _URLShortener_BatchShortenURLs_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "MonitorURLStats",
			Handler:       _URLShortener_MonitorURLStats_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/url_shortener.proto",
}
