syntax = "proto3";
package urlshortener;
option go_package = "url-shortener/proto;proto";
// Define the URL shortening service
service URLShortener {
  // Shorten a URL
  rpc ShortenURL (ShortenRequest) returns (ShortenResponse);
  // Retrieve original URL
  rpc GetOriginalURL (GetRequest) returns (GetResponse);
}
// Request to shorten a URL
message ShortenRequest {
  string original_url = 1;
}
// Response with shortened URL
message ShortenResponse {
  string short_url = 1;
}
// Request to retrieve original URL
message GetRequest {
  string short_url = 1;
}
// Response with original URL
message GetResponse {
  string original_url = 1;
}