version: '3.8'
services:
  cli:
    build: .
    container_name: cli-container
    restart: unless-stopped
    tty: true
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/db?sslmode=disable
      - TZ=Asia/Taipei
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      TZ: Asia/Taipei
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data:
    driver: local